---
- name: Boilerplate Setup
  hosts: localhost
  vars_prompt:
    - name: project_name
      prompt: What is the name of the project (ex. test-app)?
      private: no

    - name: app_type
      prompt: What framework will your app use (react/express/next)?
      private: no

    - name: github_repo
      prompt: What is your github repository url?
      private: no

    - name: github_user
      prompt: What is your github username?
      private: no

    - name: github_password
      prompt: What is your github PAT (personal access token)?
      private: yes

    - name: container_registry_repository
      prompt: What is your container registry repository adress?
      private: no

    - name: container_registry_user
      prompt: What is your container registry user?
      private: no

    - name: container_registry_encoded_json
      prompt: What is your container registry encoded json secret?
      private: yes

  roles:
    - new-project-boilerplate